// Zero Runtime (ZRT) gRPC Protocol
//
// NOTE: the `package` and `service` names below define the gRPC wire path the
// runtime serves (e.g. /agent_runtime.v1.AgentRuntime/EventStream). They must
// stay in lockstep with the runtime — do NOT rename them here alone or the SDK
// will fail to connect. Only the file/module name is ZRT-branded.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: zrt_runtime.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentRuntime_CreateSession_FullMethodName       = "/agent_runtime.v1.AgentRuntime/CreateSession"
	AgentRuntime_DestroySession_FullMethodName      = "/agent_runtime.v1.AgentRuntime/DestroySession"
	AgentRuntime_GetSessionInfo_FullMethodName      = "/agent_runtime.v1.AgentRuntime/GetSessionInfo"
	AgentRuntime_Health_FullMethodName              = "/agent_runtime.v1.AgentRuntime/Health"
	AgentRuntime_InjectMessage_FullMethodName       = "/agent_runtime.v1.AgentRuntime/InjectMessage"
	AgentRuntime_RemoveMessage_FullMethodName       = "/agent_runtime.v1.AgentRuntime/RemoveMessage"
	AgentRuntime_GetContext_FullMethodName          = "/agent_runtime.v1.AgentRuntime/GetContext"
	AgentRuntime_ClearContext_FullMethodName        = "/agent_runtime.v1.AgentRuntime/ClearContext"
	AgentRuntime_EventStream_FullMethodName         = "/agent_runtime.v1.AgentRuntime/EventStream"
	AgentRuntime_SendA2AMessage_FullMethodName      = "/agent_runtime.v1.AgentRuntime/SendA2AMessage"
	AgentRuntime_SipGetCallInfo_FullMethodName      = "/agent_runtime.v1.AgentRuntime/SipGetCallInfo"
	AgentRuntime_SipCreateRoom_FullMethodName       = "/agent_runtime.v1.AgentRuntime/SipCreateRoom"
	AgentRuntime_SipMakeOutboundCall_FullMethodName = "/agent_runtime.v1.AgentRuntime/SipMakeOutboundCall"
	AgentRuntime_SipSwitchCallRoom_FullMethodName   = "/agent_runtime.v1.AgentRuntime/SipSwitchCallRoom"
	AgentRuntime_SipListRoomCalls_FullMethodName    = "/agent_runtime.v1.AgentRuntime/SipListRoomCalls"
	AgentRuntime_SipEndCall_FullMethodName          = "/agent_runtime.v1.AgentRuntime/SipEndCall"
	AgentRuntime_LlmComplete_FullMethodName         = "/agent_runtime.v1.AgentRuntime/LlmComplete"
	AgentRuntime_RegisterAgent_FullMethodName       = "/agent_runtime.v1.AgentRuntime/RegisterAgent"
	AgentRuntime_Dispatch_FullMethodName            = "/agent_runtime.v1.AgentRuntime/Dispatch"
	AgentRuntime_Terminate_FullMethodName           = "/agent_runtime.v1.AgentRuntime/Terminate"
	AgentRuntime_TestEmitToolCall_FullMethodName    = "/agent_runtime.v1.AgentRuntime/TestEmitToolCall"
)

// AgentRuntimeClient is the client API for AgentRuntime service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentRuntimeClient interface {
	CreateSession(ctx context.Context, in *SessionConfig, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	DestroySession(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error)
	GetSessionInfo(ctx context.Context, in *SessionInfoRequest, opts ...grpc.CallOption) (*SessionInfo, error)
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	InjectMessage(ctx context.Context, in *InjectMessageRequest, opts ...grpc.CallOption) (*ContextOpResult, error)
	RemoveMessage(ctx context.Context, in *RemoveMessageRequest, opts ...grpc.CallOption) (*ContextOpResult, error)
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error)
	ClearContext(ctx context.Context, in *ClearContextRequest, opts ...grpc.CallOption) (*ContextOpResult, error)
	EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientEvent, RuntimeEvent], error)
	SendA2AMessage(ctx context.Context, in *A2AMessageRequest, opts ...grpc.CallOption) (*A2AMessageResponse, error)
	SipGetCallInfo(ctx context.Context, in *SipGetCallInfoRequest, opts ...grpc.CallOption) (*SipGetCallInfoResponse, error)
	SipCreateRoom(ctx context.Context, in *SipCreateRoomRequest, opts ...grpc.CallOption) (*SipCreateRoomResponse, error)
	SipMakeOutboundCall(ctx context.Context, in *SipMakeOutboundCallRequest, opts ...grpc.CallOption) (*SipMakeOutboundCallResponse, error)
	SipSwitchCallRoom(ctx context.Context, in *SipSwitchCallRoomRequest, opts ...grpc.CallOption) (*SipSwitchCallRoomResponse, error)
	SipListRoomCalls(ctx context.Context, in *SipListRoomCallsRequest, opts ...grpc.CallOption) (*SipListRoomCallsResponse, error)
	SipEndCall(ctx context.Context, in *SipEndCallRequest, opts ...grpc.CallOption) (*SipEndCallResponse, error)
	LlmComplete(ctx context.Context, in *LlmCompleteRequest, opts ...grpc.CallOption) (*LlmCompleteResponse, error)
	// Registered-agent mode: SDK registers once, runtime pushes dispatched sessions.
	RegisterAgent(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentStreamIn, AgentStreamOut], error)
	// api-server-facing: requests a new session on a registered agent matching agent_kind/labels.
	Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error)
	// api-server-facing: terminates a session.
	Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error)
}

type agentRuntimeClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentRuntimeClient(cc grpc.ClientConnInterface) AgentRuntimeClient {
	return &agentRuntimeClient{cc}
}

func (c *agentRuntimeClient) CreateSession(ctx context.Context, in *SessionConfig, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) DestroySession(ctx context.Context, in *DestroyRequest, opts ...grpc.CallOption) (*DestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_DestroySession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) GetSessionInfo(ctx context.Context, in *SessionInfoRequest, opts ...grpc.CallOption) (*SessionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SessionInfo)
	err := c.cc.Invoke(ctx, AgentRuntime_GetSessionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) InjectMessage(ctx context.Context, in *InjectMessageRequest, opts ...grpc.CallOption) (*ContextOpResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextOpResult)
	err := c.cc.Invoke(ctx, AgentRuntime_InjectMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) RemoveMessage(ctx context.Context, in *RemoveMessageRequest, opts ...grpc.CallOption) (*ContextOpResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextOpResult)
	err := c.cc.Invoke(ctx, AgentRuntime_RemoveMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) ClearContext(ctx context.Context, in *ClearContextRequest, opts ...grpc.CallOption) (*ContextOpResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContextOpResult)
	err := c.cc.Invoke(ctx, AgentRuntime_ClearContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) EventStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ClientEvent, RuntimeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentRuntime_ServiceDesc.Streams[0], AgentRuntime_EventStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ClientEvent, RuntimeEvent]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_EventStreamClient = grpc.BidiStreamingClient[ClientEvent, RuntimeEvent]

func (c *agentRuntimeClient) SendA2AMessage(ctx context.Context, in *A2AMessageRequest, opts ...grpc.CallOption) (*A2AMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(A2AMessageResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SendA2AMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipGetCallInfo(ctx context.Context, in *SipGetCallInfoRequest, opts ...grpc.CallOption) (*SipGetCallInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipGetCallInfoResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipGetCallInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipCreateRoom(ctx context.Context, in *SipCreateRoomRequest, opts ...grpc.CallOption) (*SipCreateRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipCreateRoomResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipCreateRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipMakeOutboundCall(ctx context.Context, in *SipMakeOutboundCallRequest, opts ...grpc.CallOption) (*SipMakeOutboundCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipMakeOutboundCallResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipMakeOutboundCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipSwitchCallRoom(ctx context.Context, in *SipSwitchCallRoomRequest, opts ...grpc.CallOption) (*SipSwitchCallRoomResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipSwitchCallRoomResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipSwitchCallRoom_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipListRoomCalls(ctx context.Context, in *SipListRoomCallsRequest, opts ...grpc.CallOption) (*SipListRoomCallsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipListRoomCallsResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipListRoomCalls_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipEndCall(ctx context.Context, in *SipEndCallRequest, opts ...grpc.CallOption) (*SipEndCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipEndCallResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipEndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) LlmComplete(ctx context.Context, in *LlmCompleteRequest, opts ...grpc.CallOption) (*LlmCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmCompleteResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_LlmComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) SipEndCall(ctx context.Context, in *SipEndCallRequest, opts ...grpc.CallOption) (*SipEndCallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SipEndCallResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_SipEndCall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) LlmComplete(ctx context.Context, in *LlmCompleteRequest, opts ...grpc.CallOption) (*LlmCompleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LlmCompleteResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_LlmComplete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) Dispatch(ctx context.Context, in *DispatchRequest, opts ...grpc.CallOption) (*DispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DispatchResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Dispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentRuntimeClient) Terminate(ctx context.Context, in *TerminateRequest, opts ...grpc.CallOption) (*TerminateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateResponse)
	err := c.cc.Invoke(ctx, AgentRuntime_Terminate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentRuntimeServer is the server API for AgentRuntime service.
// All implementations must embed UnimplementedAgentRuntimeServer
// for forward compatibility.
type AgentRuntimeServer interface {
	CreateSession(context.Context, *SessionConfig) (*CreateSessionResponse, error)
	DestroySession(context.Context, *DestroyRequest) (*DestroyResponse, error)
	GetSessionInfo(context.Context, *SessionInfoRequest) (*SessionInfo, error)
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	InjectMessage(context.Context, *InjectMessageRequest) (*ContextOpResult, error)
	RemoveMessage(context.Context, *RemoveMessageRequest) (*ContextOpResult, error)
	GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error)
	ClearContext(context.Context, *ClearContextRequest) (*ContextOpResult, error)
	EventStream(grpc.BidiStreamingServer[ClientEvent, RuntimeEvent]) error
	SendA2AMessage(context.Context, *A2AMessageRequest) (*A2AMessageResponse, error)
	SipGetCallInfo(context.Context, *SipGetCallInfoRequest) (*SipGetCallInfoResponse, error)
	SipCreateRoom(context.Context, *SipCreateRoomRequest) (*SipCreateRoomResponse, error)
	SipMakeOutboundCall(context.Context, *SipMakeOutboundCallRequest) (*SipMakeOutboundCallResponse, error)
	SipSwitchCallRoom(context.Context, *SipSwitchCallRoomRequest) (*SipSwitchCallRoomResponse, error)
	SipListRoomCalls(context.Context, *SipListRoomCallsRequest) (*SipListRoomCallsResponse, error)
	SipEndCall(context.Context, *SipEndCallRequest) (*SipEndCallResponse, error)
	LlmComplete(context.Context, *LlmCompleteRequest) (*LlmCompleteResponse, error)
	// Registered-agent mode: SDK registers once, runtime pushes dispatched sessions.
	RegisterAgent(grpc.BidiStreamingServer[AgentStreamIn, AgentStreamOut]) error
	// api-server-facing: requests a new session on a registered agent matching agent_kind/labels.
	Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error)
	// api-server-facing: terminates a session.
	Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error)
	mustEmbedUnimplementedAgentRuntimeServer()
}

// UnimplementedAgentRuntimeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentRuntimeServer struct{}

func (UnimplementedAgentRuntimeServer) CreateSession(context.Context, *SessionConfig) (*CreateSessionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedAgentRuntimeServer) DestroySession(context.Context, *DestroyRequest) (*DestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DestroySession not implemented")
}
func (UnimplementedAgentRuntimeServer) GetSessionInfo(context.Context, *SessionInfoRequest) (*SessionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionInfo not implemented")
}
func (UnimplementedAgentRuntimeServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedAgentRuntimeServer) InjectMessage(context.Context, *InjectMessageRequest) (*ContextOpResult, error) {
	return nil, status.Error(codes.Unimplemented, "method InjectMessage not implemented")
}
func (UnimplementedAgentRuntimeServer) RemoveMessage(context.Context, *RemoveMessageRequest) (*ContextOpResult, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMessage not implemented")
}
func (UnimplementedAgentRuntimeServer) GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedAgentRuntimeServer) ClearContext(context.Context, *ClearContextRequest) (*ContextOpResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearContext not implemented")
}
func (UnimplementedAgentRuntimeServer) EventStream(grpc.BidiStreamingServer[ClientEvent, RuntimeEvent]) error {
	return status.Error(codes.Unimplemented, "method EventStream not implemented")
}
func (UnimplementedAgentRuntimeServer) SipGetCallInfo(context.Context, *SipGetCallInfoRequest) (*SipGetCallInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipGetCallInfo not implemented")
}
func (UnimplementedAgentRuntimeServer) SipCreateRoom(context.Context, *SipCreateRoomRequest) (*SipCreateRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipCreateRoom not implemented")
}
func (UnimplementedAgentRuntimeServer) SipMakeOutboundCall(context.Context, *SipMakeOutboundCallRequest) (*SipMakeOutboundCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipMakeOutboundCall not implemented")
}
func (UnimplementedAgentRuntimeServer) SipGetCallInfo(context.Context, *SipGetCallInfoRequest) (*SipGetCallInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipGetCallInfo not implemented")
}
func (UnimplementedAgentRuntimeServer) SipCreateRoom(context.Context, *SipCreateRoomRequest) (*SipCreateRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipCreateRoom not implemented")
}
func (UnimplementedAgentRuntimeServer) SipMakeOutboundCall(context.Context, *SipMakeOutboundCallRequest) (*SipMakeOutboundCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipMakeOutboundCall not implemented")
}
func (UnimplementedAgentRuntimeServer) SipSwitchCallRoom(context.Context, *SipSwitchCallRoomRequest) (*SipSwitchCallRoomResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipSwitchCallRoom not implemented")
}
func (UnimplementedAgentRuntimeServer) SipListRoomCalls(context.Context, *SipListRoomCallsRequest) (*SipListRoomCallsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipListRoomCalls not implemented")
}
func (UnimplementedAgentRuntimeServer) SipEndCall(context.Context, *SipEndCallRequest) (*SipEndCallResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SipEndCall not implemented")
}
func (UnimplementedAgentRuntimeServer) LlmComplete(context.Context, *LlmCompleteRequest) (*LlmCompleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LlmComplete not implemented")
}
func (UnimplementedAgentRuntimeServer) RegisterAgent(grpc.BidiStreamingServer[AgentStreamIn, AgentStreamOut]) error {
	return status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentRuntimeServer) Dispatch(context.Context, *DispatchRequest) (*DispatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dispatch not implemented")
}
func (UnimplementedAgentRuntimeServer) Terminate(context.Context, *TerminateRequest) (*TerminateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Terminate not implemented")
}
func (UnimplementedAgentRuntimeServer) mustEmbedUnimplementedAgentRuntimeServer() {}
func (UnimplementedAgentRuntimeServer) testEmbeddedByValue()                      {}

// UnsafeAgentRuntimeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentRuntimeServer will
// result in compilation errors.
type UnsafeAgentRuntimeServer interface {
	mustEmbedUnimplementedAgentRuntimeServer()
}

func RegisterAgentRuntimeServer(s grpc.ServiceRegistrar, srv AgentRuntimeServer) {
	// If the following call panics, it indicates UnimplementedAgentRuntimeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentRuntime_ServiceDesc, srv)
}

func _AgentRuntime_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).CreateSession(ctx, req.(*SessionConfig))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_DestroySession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).DestroySession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_DestroySession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).DestroySession(ctx, req.(*DestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_GetSessionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SessionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).GetSessionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_GetSessionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).GetSessionInfo(ctx, req.(*SessionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_InjectMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InjectMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).InjectMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_InjectMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).InjectMessage(ctx, req.(*InjectMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_RemoveMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).RemoveMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_RemoveMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).RemoveMessage(ctx, req.(*RemoveMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_ClearContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).ClearContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_ClearContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).ClearContext(ctx, req.(*ClearContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_EventStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentRuntimeServer).EventStream(&grpc.GenericServerStream[ClientEvent, RuntimeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentRuntime_EventStreamServer = grpc.BidiStreamingServer[ClientEvent, RuntimeEvent]

func _AgentRuntime_SendA2AMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(A2AMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SendA2AMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SendA2AMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SendA2AMessage(ctx, req.(*A2AMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipGetCallInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipGetCallInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipGetCallInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipGetCallInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipGetCallInfo(ctx, req.(*SipGetCallInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipCreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipCreateRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipCreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipCreateRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipCreateRoom(ctx, req.(*SipCreateRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipMakeOutboundCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipMakeOutboundCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipMakeOutboundCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipMakeOutboundCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipMakeOutboundCall(ctx, req.(*SipMakeOutboundCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipSwitchCallRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipSwitchCallRoomRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipSwitchCallRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipSwitchCallRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipSwitchCallRoom(ctx, req.(*SipSwitchCallRoomRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipListRoomCalls_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipListRoomCallsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipListRoomCalls(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipListRoomCalls_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipListRoomCalls(ctx, req.(*SipListRoomCallsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipEndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipEndCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipEndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipEndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipEndCall(ctx, req.(*SipEndCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_LlmComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).LlmComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_LlmComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).LlmComplete(ctx, req.(*LlmCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_SipEndCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SipEndCallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).SipEndCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_SipEndCall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).SipEndCall(ctx, req.(*SipEndCallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_LlmComplete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LlmCompleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).LlmComplete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_LlmComplete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).LlmComplete(ctx, req.(*LlmCompleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_Dispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Dispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Dispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Dispatch(ctx, req.(*DispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentRuntime_Terminate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentRuntimeServer).Terminate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentRuntime_Terminate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentRuntimeServer).Terminate(ctx, req.(*TerminateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentRuntime_ServiceDesc is the grpc.ServiceDesc for AgentRuntime service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentRuntime_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent_runtime.v1.AgentRuntime",
	HandlerType: (*AgentRuntimeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _AgentRuntime_CreateSession_Handler,
		},
		{
			MethodName: "DestroySession",
			Handler:    _AgentRuntime_DestroySession_Handler,
		},
		{
			MethodName: "GetSessionInfo",
			Handler:    _AgentRuntime_GetSessionInfo_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _AgentRuntime_Health_Handler,
		},
		{
			MethodName: "InjectMessage",
			Handler:    _AgentRuntime_InjectMessage_Handler,
		},
		{
			MethodName: "RemoveMessage",
			Handler:    _AgentRuntime_RemoveMessage_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _AgentRuntime_GetContext_Handler,
		},
		{
			MethodName: "ClearContext",
			Handler:    _AgentRuntime_ClearContext_Handler,
		},
		{
			MethodName: "SendA2AMessage",
			Handler:    _AgentRuntime_SendA2AMessage_Handler,
		},
		{
			MethodName: "SipGetCallInfo",
			Handler:    _AgentRuntime_SipGetCallInfo_Handler,
		},
		{
			MethodName: "SipCreateRoom",
			Handler:    _AgentRuntime_SipCreateRoom_Handler,
		},
		{
			MethodName: "SipMakeOutboundCall",
			Handler:    _AgentRuntime_SipMakeOutboundCall_Handler,
		},
		{
			MethodName: "SipSwitchCallRoom",
			Handler:    _AgentRuntime_SipSwitchCallRoom_Handler,
		},
		{
			MethodName: "SipListRoomCalls",
			Handler:    _AgentRuntime_SipListRoomCalls_Handler,
		},
		{
			MethodName: "SipEndCall",
			Handler:    _AgentRuntime_SipEndCall_Handler,
		},
		{
			MethodName: "LlmComplete",
			Handler:    _AgentRuntime_LlmComplete_Handler,
		},
		{
			MethodName: "Dispatch",
			Handler:    _AgentRuntime_Dispatch_Handler,
		},
		{
			MethodName: "Terminate",
			Handler:    _AgentRuntime_Terminate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventStream",
			Handler:       _AgentRuntime_EventStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "zrt_runtime.proto",
}
